const assert=require('node:assert/strict');
const api=require('../assets/cloud-kv-peer-manager.js');
const t=api._test;
const resident={installed:true,exact_readback_verified:true,instance:{instance_id:'kvi_11111111111111111111111111111111',instance_number:1,kv_set_id:'personal',storage:{medium:'device-local-browser-indexeddb'}}};
const created=t.buildCreate(resident,{storage_medium:'icloud-drive',requested_instance_number:2,storage_locator_hint:'iCloud Drive/StegVerse'});
assert.equal(created.schema,'stegverse.site.cloud-kv-peer-create-request/v1');
assert.equal(created.operation,'CREATE_CLOUD_KV_PEER');
assert.equal(created.requested_instance_number,2);
assert.equal(created.initial_relationship_tier,'NOT_CONNECTED');
assert.equal(created.governance_state,'PENDING_INTERLOCK_INTR');
assert.equal(created.credential_destination,'SKAP_VAULT');
assert.equal(created.credential_material_present,false);
assert.equal(created.provider_operation_authorized,false);
assert.equal(created.instance_materialized,false);
assert.equal(created.relationship_mutation_authorized,false);
assert.equal(created.data_moved,false);
assert.equal(created.replication_started,false);
assert.equal(created.ai_corpus_exposed,false);
assert.equal(created.authority_effect,'NONE_REQUEST_ONLY');
assert.equal(created.activation_effect,false);
api.validate(created);
const adopted=t.buildAdopt(resident,{storage_medium:'google-drive',requested_instance_number:2,current_instance_number:1,existing_instance_id:'kvi_a31335d2cc3745fa987b635432cfed2c',existing_receipt_sha256:'sha256:f00378cd1f68e08a39c837f2a80e7e105e822a321c0eea17a91318b4b6e5ea19',existing_projection_sha256:'sha256:187ab43f0bb09d88da154af26d57e1bfe7199fd90affd2dd81af5532f0e34cf4'});
assert.equal(adopted.schema,'stegverse.site.cloud-kv-peer-adoption-request/v1');
assert.equal(adopted.operation,'ADOPT_EXISTING_CLOUD_KV_PEER');
assert.equal(adopted.ordinal_reassignment_requested,true);
assert.equal(adopted.private_content_rewrite_authorized,false);
assert.equal(adopted.existing_identity_rewrite_authorized,false);
assert.equal(adopted.provenance_preservation_required,true);
api.validate(adopted);
assert.throws(()=>t.requireResidentStatus({installed:false}),/resident device-local KV/);
assert.throws(()=>t.buildCreate(resident,{storage_medium:'ftp',requested_instance_number:2}),/unsupported cloud provider/);
assert.throws(()=>t.buildCreate(resident,{storage_medium:'google-drive',requested_instance_number:1}),/ordinal must be >= 2/);
assert.throws(()=>t.buildCreate(resident,{storage_medium:'google-drive',requested_instance_number:2,storage_locator_hint:'access_token=bad'}),/forbidden credential-like material/);
assert.deepEqual(api.supported_storage_media,['icloud-drive','google-drive','onedrive','dropbox']);
console.log('CLOUD_KV_PEER_MANAGER=PASS');
console.log('RESIDENT_KV_REQUIRED=TRUE');
console.log('CLOUD_PEER_DEFAULT_RELATIONSHIP=NOT_CONNECTED');
console.log('CLOUD_PROVIDER_EXECUTION_AUTHORITY=NONE');
console.log('EXISTING_GOOGLE_DRIVE_PROVENANCE_PRESERVED=TRUE');
