const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {webcrypto}=require('node:crypto');
globalThis.crypto=webcrypto;
globalThis.StegVerseGeneratedInTr={canonical(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(this.canonical.bind(this)).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+this.canonical(v[k])).join(',')+'}';}};
const bridge=require('../assets/cloud-kv-adoption-device-kv-bridge.js');
const profile=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/kv/google-drive-existing-peer-adoption-profile.json'),'utf8'));
assert.equal(profile.schema,'stegverse.site.cloud-kv-existing-peer-prepared-profile/v1');
assert.equal(profile.storage_medium,'google-drive');
assert.equal(profile.current_instance_number,1);
assert.equal(profile.requested_instance_number,2);
assert.match(profile.existing_instance_id,/^kvi_[a-f0-9]{32}$/);
assert.match(profile.existing_receipt_sha256,/^sha256:[a-f0-9]{64}$/);
assert.match(profile.existing_projection_sha256,/^sha256:[a-f0-9]{64}$/);
assert.equal(profile.private_content_rewrite_authorized,false);
assert.equal(profile.existing_identity_rewrite_authorized,false);
assert.equal(profile.provenance_preservation_required,true);
assert.equal(profile.provider_operation_authorized,false);
assert.equal(profile.relationship_mutation_authorized,false);
const request={
 schema:'stegverse.site.cloud-kv-peer-adoption-request/v1',operation:'ADOPT_EXISTING_CLOUD_KV_PEER',purpose:'test',request_id:'SITE-CLOUD-KV-0123456789abcdef0123456789abcdef',resident_instance_id:'kvi_0d5d4cfd531db51bbcf7fdfc0311f5dc',resident_instance_number:1,kv_set_id:'personal',requested_instance_number:2,requested_logical_name:'KV #2',storage_medium:'google-drive',initial_relationship_tier:'NOT_CONNECTED',governance_state:'PENDING_INTERLOCK_INTR',credential_destination:'SKAP_VAULT',credential_material_present:false,provider_operation_authorized:false,instance_materialized:false,relationship_mutation_authorized:false,data_moved:false,replication_started:false,ai_corpus_exposed:false,authority_effect:'NONE_REQUEST_ONLY',activation_effect:false,
 existing_cloud_identity:{instance_id:profile.existing_instance_id,current_instance_number:1,requested_instance_number:2,installation_or_adoption_receipt_sha256:profile.existing_receipt_sha256,set_projection_sha256:profile.existing_projection_sha256},storage_locator_hint:null,ordinal_reassignment_requested:true,private_content_rewrite_authorized:false,existing_identity_rewrite_authorized:false,provenance_preservation_required:true
};
bridge._test.validateRequest(request);
const envelope=bridge._test.buildEnvelope('SV-NODE-test',request);
assert.equal(envelope.record_class,'MY_KV_CLOUD_PEER_ADOPTION_REQUEST');
assert.equal(envelope.my_kv_request.request_id,request.request_id);
assert.equal(envelope.authority_ref,'stegos-node://SV-NODE-test');
assert.equal(envelope.credential_material_present,false);
assert.equal(envelope.provider_operation_authorized,false);
assert.equal(envelope.relationship_mutation_authorized,false);
assert.equal(envelope.authority_effect,'NONE_REQUEST_ONLY');
assert.equal(envelope.activation_effect,false);
assert.throws(()=>bridge._test.validateRequest({...request,instance_materialized:true}),/claimed runtime effects/);
assert.throws(()=>bridge._test.validateRequest({...request,provider_operation_authorized:true}),/credential\/provider boundary/);
assert.throws(()=>bridge._test.validateRequest({...request,private_content_rewrite_authorized:true}),/provenance boundary/);
assert.throws(()=>bridge._test.validateRequest({...request,governance_state:'ALLOW'}),/governance boundary/);
const receiver=fs.readFileSync(path.join(__dirname,'../assets/cloud-kv-adoption-device-kv-receiver.js'),'utf8');
for(const marker of ['MY_KV_CLOUD_PEER_ADOPTION_REQUEST','PENDING_INTERLOCK_INTR','resident_ingress_observed:true','provider_execution_attempted:false','relationship_mutation_attempted:false','instance_materialized:false','data_moved:false','replication_started:false','ai_corpus_exposed:false','credential_authority:"TV/TVC"','github_token_runtime_authority:"NONE"','NONE_RESULT_DELIVERY_ONLY'])assert.ok(receiver.includes(marker),'missing receiver marker '+marker);
for(const forbidden of ['provider_execution_attempted:true','relationship_mutation_attempted:true','instance_materialized:true','data_moved:true','replication_started:true','ai_corpus_exposed:true','provider_operation_authorized:true','relationship_mutation_authorized:true'])assert.equal(receiver.includes(forbidden),false,'prohibited receiver marker '+forbidden);
const page=fs.readFileSync(path.join(__dirname,'../cloud-kv-peers.html'),'utf8');
assert.ok(page.includes('Emit governed Google Drive KV #2 adoption request'));
assert.ok(page.includes('No file selection or hash entry required'));
assert.ok(page.includes('cloud-kv-adoption-device-kv-bridge.js'));
assert.equal(page.includes('1c8OdhJeLD6E4ALmi-aR7dXvG8PjDLSfi'),false,'private Drive locator leaked into public page');
console.log('CLOUD_KV_ADOPTION_RESIDENT_TRANSPORT=PASS');
console.log('GOOGLE_DRIVE_KV2_PREPARED_INPUT=PASS');
console.log('CLOUD_KV_ADOPTION_PROVIDER_EXECUTION=FALSE');
console.log('CLOUD_KV_ADOPTION_RELATIONSHIP_MUTATION=FALSE');
