const assert = require('node:assert/strict');
const api = require('../assets/device-local-kv-installer.js');
const t = api._test;
const nodeId = 'SV-NODE-test-device';
const instanceId = 'kvi_0123456789abcdef0123456789abcdef';
const created = '2026-09-08T23:59:00.000Z';
const instance = t.buildInstance(nodeId, instanceId, created);
assert.equal(instance.schema, 'stegverse.kv.instance/v1');
assert.equal(instance.instance_number, 1);
assert.equal(instance.logical_name, 'KV #1');
assert.equal(instance.kv_set_id, 'personal');
assert.equal(instance.storage.medium, 'device-local-browser-indexeddb');
assert.equal(instance.resident.node_id, nodeId);
assert.equal(instance.resident.device_local, true);
assert.equal(instance.relationship.tier, 'NOT_CONNECTED');
assert.equal(instance.relationship.inter_comms, false);
assert.equal(instance.relationship.data_movement, false);
assert.equal(instance.relationship.replication, false);
assert.equal(instance.relationship.unified_ai_corpus, false);
assert.equal(instance.authority_effect, 'NONE');
assert.equal(instance.activation_effect, false);
t.validateInstance(instance, nodeId);
const receipt = t.buildReceipt(nodeId, instance, created, {requested:true,granted:false});
assert.equal(receipt.schema, 'stegverse.kv.device-local-installation-receipt/v1');
assert.equal(receipt.schema_version, '1.1');
assert.equal(receipt.instance.instance_id, instanceId);
assert.equal(receipt.destination, 'indexeddb:stegverse-device-local-kv-v1/files');
assert.equal(receipt.credential_material_present, false);
assert.equal(receipt.provider_operation_authorized, false);
assert.equal(receipt.relationship_mutation_authorized, false);
assert.equal(receipt.authority_effect, 'NONE');
assert.equal(receipt.activation_effect, false);
const projection = t.buildProjection(instance);
t.validateProjection(projection, instanceId);
assert.equal(projection.schema, 'stegverse.kv.my-kv-set-projection/v1');
assert.equal(projection.instance_count, 1);
assert.equal(projection.instances[0].providers.provider_mutation_authorized, false);
assert.equal(projection.instances[0].providers.credential_material_included, false);
assert.equal(projection.instances[0].management.relationship_mutation_authorized, false);
assert.equal(projection.instances[0].relationship.tier, 'NOT_CONNECTED');
assert.equal(projection.private_content_included, false);
assert.equal(projection.credential_material_included, false);
assert.equal(projection.authority_effect, 'NONE_STATUS_ONLY');
assert.equal(projection.activation_effect, false);
assert.throws(() => t.validateInstance({...instance, storage:{...instance.storage, medium:'google-drive'}}, nodeId), /device-local storage binding invalid/);
assert.throws(() => t.validateProjection({...projection, private_content_included:true}, instanceId), /set projection authority invalid/);
assert.equal(t.paths.instance, '_System/Instances/instance.json');
assert.equal(t.paths.receipt, '_System/installation.receipt.json');
assert.equal(t.paths.projection, '_System/my-kv-set-projection.json');
console.log('DEVICE_LOCAL_KV_INSTALLER=PASS');
console.log('DEVICE_LOCAL_KV_DB=stegverse-device-local-kv-v1');
console.log('DEVICE_LOCAL_KV_TRANSPORT_DB_SEPARATION=PASS');
console.log('DEVICE_LOCAL_KV_DEFAULT_RELATIONSHIP=NOT_CONNECTED');
console.log('DEVICE_LOCAL_KV_AUTHORITY_EFFECT=NONE');
