name: Multi Deploy & Purge

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy UI (Render)
        if: ${{ secrets.RENDER_UI_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.RENDER_UI_DEPLOY_HOOK }}" -H "Content-Type: application/json" -d '{"source":"gh"}'
      - name: Deploy API (Render)
        if: ${{ secrets.RENDER_API_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.RENDER_API_DEPLOY_HOOK }}" -H "Content-Type: application/json" -d '{"source":"gh"}'
      - name: Deploy Worker (Render)
        if: ${{ secrets.RENDER_WORKER_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.RENDER_WORKER_DEPLOY_HOOK }}" -H "Content-Type: application/json" -d '{"source":"gh"}'

      - name: Purge Cloudflare
        if: ${{ secrets.CF_ZONE_ID != '' && secrets.CF_API_TOKEN != '' }}
        run: |
          curl -fsSL -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'

      - name: Wait a bit
        run: sleep 8

      - name: Smoke check API
        run: |
          curl -fsS https://scw-api.onrender.com/whoami | sed -e 's/.*/API OK: &/'
