name: pages
on: {push: {branches: [main]}, workflow_dispatch: {}}
permissions: {pages: write, id-token: write, contents: write}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure site files
        run: |
          mkdir -p .
          [ -f index.html ] || echo '<!doctype html><title>StegVerse</title><h1>StegVerse</h1><p>Sovereign, verifiable, resilient.</p><p><a href="status.html">Status</a></p>' > index.html
          echo '{"ok":true,"ts":"'$(date -u +%FT%TZ)'"}' > status.json
          echo '<!doctype html><title>Status</title><h1>Status</h1><pre>'$(cat status.json)'</pre><p><a href="index.html">Home</a></p>' > status.html
      - uses: actions/upload-pages-artifact@v3
        with: {path: "."}
      - uses: actions/deploy-pages@v4
